spring:
  application:
    name: polaris-web-management      //注意把yml文件中跟个人有关的配置改成自己的
  datasource:
    url: jdbc:mysql://localhost:3306/polaris
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 251147
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucketName: baifantuan-java-ai
    region: cn-guangzhou
